name: "🐛 Bug Report"
description: Report a bug or issue
title: "[BUG] "
labels: ["type: bug", "status: triage"]
body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How critical is this issue?
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true
  
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the system?
      options:
        - Frontend
        - Backend
        - API
        - Database
        - Infrastructure
    validations:
      required: true
  
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where did this occur?
      options:
        - Production
        - Staging
        - Dev
    validations:
      required: true
  
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed list of steps
      value: |
        1. Go to...
        2. Click on...
        3. See error
    validations:
      required: true
  
  - type: textarea
    id: expected_actual
    attributes:
      label: Expected vs Actual
      description: Clear comparison
      value: |
        **Expected:** What should happen
        **Actual:** What actually happens
    validations:
      required: true
  
  - type: input
    id: contact
    attributes:
      label: Contact Info
      description: Optional but helpful - email or Slack handle
      placeholder: your.email@company.com or @slack-handle