name: "🐛 Bug Report"
description: Report a bug or issue
title: "[BUG] "
labels: ["type: bug", "status: triage"]
body:
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Critical (System down)
        - High (Feature broken)
        - Medium (Partial issue)
        - Low (Minor issue)
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: What's happening?
      description: Clear description of the bug
    validations:
      required: true
  
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      value: |
        1. Go to...
        2. Click on...
        3. See error
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Expected vs Actual
      value: |
        **Expected:** What should happen
        **Actual:** What actually happens
    validations:
      required: true
  
  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        - Browser: Chrome 91
        - OS: Windows 10
        - Version: v2.1.0