name: Check Commit Author
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dguo/check-author-and-committer-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          committer-email-regex: '@rihal\.om|@users\.noreply\.github\.com|@github\.com$'
          author-email-regex: '@rihal\.om|@users\.noreply\.github\.com|@github\.com$'
