name: Semantic PR
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            docs
            style
            refactor
            test
            chore
            perf
            revert
          scopes: |
            web
            server
            docker
            k8s
            e2e
            docs
            ci
            deps
            ml
            strapi
          requireScope: false
          ignoreLabels: |
            bot
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
          validateSingleCommit: true
          wip: true
